version: '3.4'

networks:
  frontend:
  backend:
services:
  catalog:
    image: jewels/catalogapi
    build:
      context: .\ProductCatalogAPI
      dockerfile: Dockerfile
    environment:
      ExternalCatalogBaseUrl: http://localhost:6811
      DatabaseServer: mssqlserver
      DatabaseName: catalogDb
      DatabaseUser: sa
      DatabasePassword: ProductApi(!)
    ports:
      - "6811:80"
    container_name: jewelscatalogapi
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlserver

  webmvc:
    image: jewels/webmvc
    build:
      context: .\WebMvc
      dockerfile: Dockerfile
    environment:
      CatalogUrl: http://catalog
      CartUrl: http://cart
      IdentityUrl: http://192.168.86.121:6703
      CallBackUrl: http://localhost:6812
      OrderUrl: http://order
      StripePublicKey: pk_test_51HD0nOKoXJmUbPfzIe8C9oKQhMLGVHNYqZBWJMA2t1jQIYt7ti2JYpwWhoDB5JwZ7o9xxgoFHZKw3VsKesAmEyDk00NiohAdBa
      StripePrivateKey: sk_test_51HD0nOKoXJmUbPfz58AR154bpVLSeq4W5HrwiGlnJAiiXywQPbpChKxQNxCA0z4xJs32HiejoYr0agbCpNgSC1Vg000Gw5mE1U
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "6812:80"
    container_name: jewelswebmvc
    networks:
      - frontend
    depends_on:
      - catalog
      - cart
      - order
      - tokenserver

  tokenserver:
    build:
      context: .\TokenServiceApi
      dockerfile: Dockerfile
    image: jewels/tokenapi
    environment:
      Mvcclient: http://localhost:6812
    ports:
      - "6703:80"
    container_name: tokenserviceapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  cart:
    build:
      context: .\CartApi
      dockerfile: Dockerfile
    image: jewels/cartapi
    environment: 
      IdentityUrl: http://192.168.86.121:6703
      ConnectionString: basket.data
    ports:
      - "6814:80"
    container_name: cartapi
    networks:
      - backend
      - frontend
    depends_on:
      - tokenserver
      - basket.data
      - rabbitmq

  order:
    build:
      context: .\OrderApi
      dockerfile: Dockerfile
    image: jewels/orderapi
    logging:
      driver: "json-file"
      options: {
          max-size: "200k",
          max-file: "10"
      }
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      IdentityUrl:  http://192.168.86.121:6703
      DatabaseServer: mssqlserver
      DatabaseName: OrdersDb
      DatabaseUser: sa
      DatabasePassword: ProductApi(!)
    ports:
      - "6815:80"
    container_name: orderapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver
      - tokenserver
      - rabbitmq
      
  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ProductApi(!)
    ports:
      - "1449:1433"
    container_name: jewelssqlserver
    networks:
      - backend

  basket.data:
    image: redis
    container_name: basketdata
    ports:
      - "6080:6379"
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: myjewelsrabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5671:5671"
    volumes:
      - ~/rabbitmq:/var/lib/rabbitmq/mnesia
    networks:
      - backend